import { ConstantItem, FormulaItem } from './types.ts';

export const SCIENTIFIC_CONSTANTS: ConstantItem[] = [
  {
    symbol: 'π',
    displaySymbol: 'π',
    name: 'Pi',
    value: '3.141592653589793',
    numericValue: Math.PI,
    description: 'Ratio of a circle’s circumference to its diameter',
    category: 'Mathematical',
  },
  {
    symbol: 'e',
    displaySymbol: 'e',
    name: 'Euler’s Number',
    value: '2.718281828459045',
    numericValue: Math.E,
    description: 'Base of natural logarithms, growth limit constant',
    category: 'Mathematical',
  },
  {
    symbol: '1.6180339887',
    displaySymbol: 'φ',
    name: 'Golden Ratio (phi)',
    value: '1.618033988749895',
    numericValue: 1.618033988749895,
    description: 'Geometric proportion of divine harmonic symmetry',
    category: 'Mathematical',
  },
  {
    symbol: '299792458',
    displaySymbol: 'c',
    name: 'Speed of Light in Vacuum',
    value: '299792458',
    numericValue: 299792458,
    unit: 'm/s',
    description: 'Universal physical constant in relativistic physics',
    category: 'Physical',
  },
  {
    symbol: '6.62607015e-34',
    displaySymbol: 'h',
    name: 'Planck Constant',
    value: '6.62607015e-34',
    numericValue: 6.62607015e-34,
    unit: 'J·s',
    description: 'Fundamental quantum of action in physics',
    category: 'Physical',
  },
  {
    symbol: '6.67430e-11',
    displaySymbol: 'G',
    name: 'Newtonian Gravitational Constant',
    value: '6.67430e-11',
    numericValue: 6.67430e-11,
    unit: 'm³/(kg·s²)',
    description: 'Proportionality constant in Newton’s law of gravitation',
    category: 'Physical',
  },
  {
    symbol: '1.380649e-23',
    displaySymbol: 'k_B',
    name: 'Boltzmann Constant',
    value: '1.380649e-23',
    numericValue: 1.380649e-23,
    unit: 'J/K',
    description: 'Relates mean kinetic energy of gas particles with temperature',
    category: 'Physical',
  },
  {
    symbol: '6.02214076e23',
    displaySymbol: 'N_A',
    name: 'Avogadro Constant',
    value: '6.02214076e23',
    numericValue: 6.02214076e23,
    unit: 'mol⁻¹',
    description: 'Number of constituent particles in one mole of substance',
    category: 'Physical',
  },
];

export const FORMULA_TEMPLATES: FormulaItem[] = [
  {
    title: 'Trigonometric Pythagorean',
    formula: 'sin(x)² + cos(x)² = 1',
    expressionToInsert: 'sin(45)^2 + cos(45)^2',
    description: 'Fundamental identity connecting sine and cosine',
    category: 'Trigonometry',
  },
  {
    title: 'Euler’s Identity Test',
    formula: 'e^(i·π) + 1 = 0',
    expressionToInsert: 'cos(180) + 1',
    description: 'Real component of Euler’s complex identity',
    category: 'Complex Analysis',
  },
  {
    title: 'Circle Area',
    formula: 'A = π · r²',
    expressionToInsert: 'π * 5^2',
    description: 'Area of circle with radius r = 5',
    category: 'Geometry',
  },
  {
    title: 'Sphere Volume',
    formula: 'V = (4/3) · π · r³',
    expressionToInsert: '(4/3) * π * 3^3',
    description: 'Volume of sphere with radius r = 3',
    category: 'Geometry',
  },
  {
    title: 'Hypotenuse (Pythagoras)',
    formula: 'c = √(a² + b²)',
    expressionToInsert: 'sqrt(3^2 + 4^2)',
    description: 'Pythagorean right-triangle hypotenuse calculation',
    category: 'Geometry',
  },
  {
    title: 'Compound Interest',
    formula: 'A = P · (1 + r/n)^(n·t)',
    expressionToInsert: '1000 * (1 + 0.05/12)^(12*5)',
    description: '$1000 principal at 5% annual interest over 5 years',
    category: 'Finance & Growth',
  },
];
